# Lokio Configuration File
# Author: Lokio
# Github: https://github.com/any-source/lokio
# Documentation: https://lokio.dev

name: backend-golang
package: your-package

# Directory
dir:
  # client
  go_controller: internal/delivery/http/controller