# Lokio Configuration File
# Author: Lokio
# Github: https://github.com/any-source/lokio
# Documentation: https://lokio.dev

name: backend-golang
package: your-package

# Directory
dir:
  # client
  go_controller: internal/delivery/http/controller
  go_feature:
    - go_controller: internal/delivery/http/controller
    - go_middleware: internal/delivery/http/middleware
    - go_repository: internal/repository
  go_alias:
    - go_repository: internal/repository
    - go_usecase: internal/usecase