# Lokio Configuration File
# Author: Lokio
# Github: https://github.com/any-source/lokio
# Documentation: https://lokio.dev

name: frontend-vue
package: your-package

# Directory
dir:
  # client
  ts_hook: src/hooks
