# Lokio Configuration File
# Author: Lokio
# Github: https://github.com/any-source/lokio
# Documentation: https://lokio.dev

name: frontend-next
package: your-package

# Directory
dir:
  # client
  ts_hook: src/hooks
  ts_call: src/call
  ts_component: src/interfaces/components
  ts_screen: src/interfaces/screens
  ts_layout: src/interfaces/layouts
  ts_schema: src/schemas