# Lokio Configuration File
# Author: Lokio
# Github: https://github.com/any-source/lokio
# Documentation: https://lokio.dev

name: mobile-kotlin-mvvm
package: your-package

# Directory
dir:
  # client
  kt_feature: "src/main/java/{package}/{domain}/presentation/feature"
