# Lokio Configuration File
# Author: Lokio
# Github: https://github.com/any-source/lokio
# Documentation: https://lokio.dev

name: monolith-next
package: your-package

# Directory
dir:
  # client
  ts_hook: src/hooks
  ts_call: src/call
  ts_component: src/interfaces/components
  ts_screen: src/interfaces/screens
  ts_layout: src/interfaces/layouts

  # server
  ts_controller: src/server/controllers
  ts_middleware: src/server/middlewares
  ts_service: src/server/services
  ts_schema: src/server/schemas
